Repository apache/incubator-graphar, pull requests merged in 2023-01, with the labels that each got.

#53 Add release and reviewing tutorial to contributing guide
  .github/workflows/release.yml
  CONTRIBUTING.rst
Labels: documentation

#64 [Improve][Doc] Revise the README and APIs docstring of GraphAr
  README.rst
  docs/index.rst
  docs/user-guide/overview.rst
  docs/user-guide/spark-lib.rst
  examples/bgl_example.cc
  examples/construct_info_example.cc
  include/gar/graph.h
  include/gar/graph_info.h
  include/gar/reader/arrow_chunk_reader.h
  include/gar/reader/chunk_info_reader.h
  include/gar/utils/adj_list_type.h
  include/gar/utils/convert_to_arrow_type.h
  include/gar/utils/data_type.h
  include/gar/utils/file_type.h
  include/gar/utils/filesystem.h
  include/gar/utils/result.h
  include/gar/utils/status.h
  include/gar/utils/utils.h
  include/gar/utils/version_parser.h
  include/gar/utils/yaml.h
  spark/src/main/scala/com/alibaba/graphar/EdgeInfo.scala
  spark/src/main/scala/com/alibaba/graphar/VertexInfo.scala
  spark/src/main/scala/com/alibaba/graphar/reader/EdgeReader.scala
  spark/src/main/scala/com/alibaba/graphar/writer/EdgeWriter.scala
  spark/src/main/scala/com/alibaba/graphar/writer/VertexWriter.scala
  spark/src/test/scala/com/alibaba/graphar/TestGraphInfo.scala
  spark/src/test/scala/com/alibaba/graphar/TestWriter.scala
  spark/src/test/scala/com/alibaba/graphar/TransformExample.scala
  src/arrow_chunk_reader.cc
  src/arrow_chunk_writer.cc
  src/graph.cc
  src/reader_utils.cc
  test/test_chunk_info_reader.cc
  test/test_info.cc
Labels: documentation, improvement

#69 [Improve][Doc] Refine the documentation about user guide and applications
  README.rst
  docs/applications/bgl.rst
  docs/applications/graphscope.rst
  docs/applications/out-of-core.rst
  docs/user-guide/file-format.rst
  docs/user-guide/getting-started.rst
  docs/user-guide/overview.rst
  docs/user-guide/spark-lib.rst
Labels: documentation, enhancement

#71 [BugFix] Hide the interface of dependencies of GraphAr with `PRIVATE` link type
  .github/workflows/ci.yml
  CMakeLists.txt
  examples/construct_info_example.cc
  include/gar/utils/file_type.h
Labels: bugfix
